# Generated by Django 4.0.5 on 2022-06-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhood_app', '0001_initial'),
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myhood_app.neighbourhood'),
        ),
    ]
