# Generated by Django 4.0.5 on 2022-06-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='neighbourhood',
        ),
    ]
