# Generated by Django 4.0.5 on 2022-06-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.CharField(max_length=100, verbose_name='Neighbourhood Name')),
                ('hood_loc', models.CharField(max_length=100, verbose_name='Neighbourhood Location')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_name', models.CharField(max_length=100, verbose_name='Business Name')),
                ('biz_email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='myhood_app.neighbourhood')),
            ],
        ),
    ]
