# Generated by Django 4.0.5 on 2022-06-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='contact_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_image',
            field=models.ImageField(null=True, upload_to='hood_images'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('post_image', models.ImageField(null=True, upload_to='post_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='myhood_app.neighbourhood')),
            ],
        ),
    ]
